services:
  backend:
    build: .
    ports:
      - "3001:3001" 
    volumes:
      - .:/app     
    environment:
      - PORT=3001
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb://mongo:27017/taskmanager 
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
